language: rust

os:
  - linux
  - osx
  # - windows

arch:
  - amd64
  - arm64

services:
  - docker  

before_install:
- rustup component add rustfmt

# cargo test
rust:
  - stable
  - beta
jobs:
  allow_failures:
    - rust: nightly
    - os: osx
  fast_finish: true

# Cargo fmt
script:
- cargo build
- cargo test
- cargo fmt -- --check

# automatic deployment to cargo on release
# deploy:
        # only deploy on master branch
        # on:
                # branch: master
        # provider: cargo
        # token: $crates 

after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
