language: rust
before_install:
- rustup component add rustfmt

# cargo test
rust:
  - stable
  - beta
  - nightly
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true

# Cargo fmt
script:
- cargo build
- cargo test
- cargo fmt -- --check
