[package]
name = "Rust_Scan"
version = "0.1.0"
authors = ["Bee <brandon@skerritt.blog>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "1.9.3"
clap = "2.33.0"
